# Generated by Django 3.0.8 on 2020-08-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
